### PR TITLE
Updated package to use Omnipay v3 library

### PR DESCRIPTION
**Pull request by robjmills**
This is a PR to make the package compatible with V3 of the Omnipay library, which is required for Symfony 3+ and associated components.

### CODE REVIEW

**Comment by bummzack** [comment]
Thank you!

**Comment by robjmills** [comment]
No problem. I should have flagged this in the PR but this is a breaking change for users with omnipay v2 or symfony < 3 components so it should probably be tagged as a v2 release.

**Comment by bummzack** [comment]
@robjmills Yeah, I'm aware of that thanks. I changed the master branch-alias to 1.0.x-dev and will release as 1.0

**Comment by robjmills** [comment]
@bummzack awesome, i'll look out for the new release then. thanks.

**Comment by mtorromeo** [comment]
@bummzack it's been 2 years. Is there any chance that this will be released?

**Comment by bummzack** [comment]
Ouch, I just tagged the `1.0.0` release. Thanks for the reminder

**Pull request merged**
